version: "3.9"

services:
  task-app:
    build:
      context: .\
      dockerfile: Dockerfile
    container_name: digital-chief-test-task
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password